//name, flags, population, capital, region, borders;


//sample
const localData = [
 {
   CommonName: "Qualla Boundary",
   OfficialName: "Eastern Band of Cherokee Indians Territory",
   CCA3: "",
   Capitol: "Cherokee",
   Region: "Americas",
   Subregion: "North America",
   French: "Territoire de la Bande orientale des Indiens Cherokee",
   Spanish: "Territorio de la Banda Oriental de Indios Cherokee",
   Russian: "Территория Восточной группы индейцев чероки",
   FlagAltText:
     "A yellow field with the tribal seal featuring a seven-pointed star in the center within an orange and green wreath of oak leaves, representing the seven original Cherokee clans and the eternal flame of the Cherokee people.",
   Population: "14,000",
 },
 {
   CommonName: "East Turkestan",
   OfficialName: "Xinjiang Uyghur Autonomous Region",
   CCA3: "",
   Capitol: "Urumqi",
   Region: "Asia",
   Subregion: "Central Asia",
   French: "Turkestan oriental",
   Spanish: "Turkestán Oriental",
   Russian: "Восточный Туркестан",
   FlagAltText:
     "A blue field with a white crescent moon and five-pointed star, known as the Kökbayraq or sky flag, representing Turkic peoples and their connection to the eternal blue sky.",
   Population: "21,810,000",
 },
 {
   CommonName: "Quebec",
   OfficialName: "Province de Québec",
   CCA3: "QC",
   Capitol: "Quebec City",
   Region: "Americas",
   Subregion: "North America",
   French: "Québec",
   Spanish: "Quebec",
   Russian: "Квебек",
   FlagAltText:
     "A blue field with a white cross dividing it into four sections, each containing a white fleur-de-lis, representing French heritage and Catholic tradition.",
   Population: "8,501,833",
 },
 {
   CommonName: "Yakutia",
   OfficialName: "Sakha Republic",
   CCA3: "",
   Capitol: "Yakutsk",
   Region: "Asia",
   Subregion: "Northern Asia",
   French: "République de Sakha",
   Spanish: "República de Sajá",
   Russian: "Республика Саха",
   FlagAltText:
     "Four horizontal stripes of light blue, white, red, and green with a white disc in the center of the blue stripe, representing the northern sun, sky, snow, taiga, and the courage of the people.",
   Population: "1,007,058",
 },
 {
   CommonName: "Buryatia",
   OfficialName: "Republic of Buryatia",
   CCA3: "",
   Capitol: "Ulan-Ude",
   Region: "Asia",
   Subregion: "Northern Asia",
   French: "République de Bouriatie",
   Spanish: "República de Buriatia",
   Russian: "Республика Бурятия",
   FlagAltText:
     "Three horizontal stripes of blue, white, and yellow in a 2:1:1 ratio with a yellow Soyombo symbol on the blue stripe, representing the moon, sun, and fire elements of Buryat culture.",
   Population: "970,679",
 },
 {
   CommonName: "Puerto Rico",
   OfficialName: "Commonwealth of Puerto Rico",
   CCA3: "PRI",
   Capitol: "San Juan",
   Region: "Americas",
   Subregion: "Caribbean",
   French: "Porto Rico",
   Spanish: "Puerto Rico",
   Russian: "Пуэрто-Рико",
   FlagAltText:
     "Five alternating horizontal stripes of red and white with a blue triangle on the hoist side containing a white five-pointed star, representing the three branches of government and Puerto Rican identity.",
   Population: "3,191,270",
 },
 {
   CommonName: "Guam",
   OfficialName: "Territory of Guam",
   CCA3: "GUM",
   Capitol: "Hagåtña",
   Region: "Oceania",
   Subregion: "Micronesia",
   French: "Guam",
   Spanish: "Guam",
   Russian: "Гуам",
   FlagAltText:
     "A dark blue field with a red border and the territorial seal in the center, depicting a coconut palm, beach, sailboat, and cliffs representing Guam's natural beauty and maritime heritage.",
   Population: "168,999",
 },
 {
   CommonName: "American Samoa",
   OfficialName: "Territory of American Samoa",
   CCA3: "ASM",
   Capitol: "Pago Pago",
   Region: "Oceania",
   Subregion: "Polynesia",
   French: "Samoa américaines",
   Spanish: "Samoa Americana",
   Russian: "Американское Самоа",
   FlagAltText:
     "A red-edged white triangle pointing towards the hoist with a bald eagle clutching a war club and fly-whisk, flanked by blue triangles, representing the unity between the United States and Samoa.",
   Population: "58,681",
 },
 {
   CommonName: "Northern Mariana Islands",
   OfficialName: "Commonwealth of the Northern Mariana Islands",
   CCA3: "MNP",
   Capitol: "Saipan",
   Region: "Oceania",
   Subregion: "Micronesia",
   French: "Îles Mariannes du Nord",
   Spanish: "Islas Marianas del Norte",
   Russian: "Северные Марианские острова",
   FlagAltText:
     "A blue field with a white star superimposed on a gray latte stone surrounded by a traditional Carolinian mwáár floral wreath, representing the Chamorro and Carolinian peoples and their connection to the United States.",
   Population: "43,571",
 },
 {
   CommonName: "US Virgin Islands",
   OfficialName: "United States Virgin Islands",
   CCA3: "VIR",
   Capitol: "Charlotte Amalie",
   Region: "Americas",
   Subregion: "Caribbean",
   French: "Îles Vierges américaines",
   Spanish: "Islas Vírgenes de los Estados Unidos",
   Russian: "Виргинские острова США",
   FlagAltText:
     "A white field with a modified US coat of arms between the blue letters V and I, featuring a yellow eagle holding arrows and an olive branch, representing the three main islands and their relationship with the United States.",
   Population: "103,000",
 },
 {
   CommonName: "Taiwan",
   OfficialName: "Republic of China",
   CCA3: "TWN",
   Capitol: "Taipei",
   Region: "Asia",
   Subregion: "Eastern Asia",
   French: "Taïwan",
   Spanish: "Taiwán",
   Russian: "Тайвань",
   FlagAltText:
     "A red field with a dark blue canton containing a white sun with twelve triangular rays, known as the Blue Sky with a White Sun and Red Earth, representing liberty, democracy, and the livelihood of the people.",
   Population: "24,057,613",
 },
 {
   CommonName: "Hong Kong",
   OfficialName: "Hong Kong Special Administrative Region",
   CCA3: "HKG",
   Capitol: "Victoria",
   Region: "Asia",
   Subregion: "Eastern Asia",
   French: "Hong Kong",
   Spanish: "Hong Kong",
   Russian: "Гонконг",
   FlagAltText:
     "A red field with a stylized white five-petaled Bauhinia blakeana flower in the center, each petal containing a red star, representing the 'one country, two systems' principle and Hong Kong's connection to China.",
   Population: "7,779,480",
 },
 {
   CommonName: "Sápmi",
   OfficialName: "Sámi Homeland",
   CCA3: "",
   Capitol: "Kautokeino",
   Region: "Europe",
   Subregion: "Northern Europe",
   French: "Sápmi",
   Spanish: "Sápmi",
   Russian: "Сапми",
   FlagAltText:
     "A flag with vertical red and blue stripes and a central circle split red/blue, symbolizing the sun and moon.",
   Population: 80000,
 },
 {
   CommonName: "Ainu Mosir",
   OfficialName: "Ainu Mosir",
   CCA3: "",
   Capitol: "Sapporo",
   Region: "Asia",
   Subregion: "Eastern Asia",
   French: "Terre des Aïnous",
   Spanish: "Tierra Ainu",
   Russian: "Земля Айнов",
   FlagAltText:
     "A green field with a white geometric pattern and traditional Ainu motifs.",
   Population: 25000,
 },
 {
   CommonName: "Wallmapu",
   OfficialName: "Mapuche Nation",
   CCA3: "",
   Capitol: "Temuco",
   Region: "Americas",
   Subregion: "South America",
   French: "Nation Mapuche",
   Spanish: "Nación Mapuche",
   Russian: "Нация Мапуче",
   FlagAltText:
     "A blue, green, and red flag with a yellow kultrun (drum) in the center, symbolizing the Mapuche worldview.",
   Population: 2000000,
 },
 {
   CommonName: "Lakota Nation",
   OfficialName: "Oceti Sakowin",
   CCA3: "",
   Capitol: "Pine Ridge",
   Region: "Americas",
   Subregion: "North America",
   French: "Nation Lakota",
   Spanish: "Nación Lakota",
   Russian: "Нация Лакота",
   FlagAltText:
     "A sky blue field with a circle of white tipis representing the seven council fires.",
   Population: 170000,
 },
 {
   CommonName: "Guarani Territory",
   OfficialName: "Guarani Yvyrupa",
   CCA3: "",
   Capitol: "Dourados",
   Region: "Americas",
   Subregion: "South America",
   French: "Terre Guarani",
   Spanish: "Territorio Guaraní",
   Russian: "Земля Гуарани",
   FlagAltText:
     "A green and white field with a central red diamond and yellow sun, reflecting Guarani cosmology.",
   Population: 510000,
 },
 {
   CommonName: "Ogiek Territory",
   OfficialName: "Ogiek Ancestral Land",
   CCA3: "",
   Capitol: "Nessuit",
   Region: "Africa",
   Subregion: "Eastern Africa",
   French: "Terre Ogiek",
   Spanish: "Tierra Ogiek",
   Russian: "Земля Огиек",
   FlagAltText:
     "No official flag; Ogiek symbols often use trees and honeycombs representing forest life.",
   Population: 52000,
 },
 {
   CommonName: "Baka Territory",
   OfficialName: "Baka Forest",
   CCA3: "",
   Capitol: "Mindourou",
   Region: "Africa",
   Subregion: "Central Africa",
   French: "Terre Baka",
   Spanish: "Tierra Baka",
   Russian: "Земля Бака",
   FlagAltText:
     "No official flag; Baka art often features forest and animal motifs.",
   Population: 30000,
 },
 {
   CommonName: "Kurdistan",
   OfficialName: "Kurdistan Region",
   CCA3: "",
   Capitol: "Erbil",
   Region: "Asia",
   Subregion: "Western Asia",
   French: "Kurdistan",
   Spanish: "Kurdistán",
   Russian: "Курдистан",
   FlagAltText:
     "A tricolor of red, white, and green with a yellow sun disk in the center.",
   Population: 30000000,
 },
 {
   CommonName: "West Papua",
   OfficialName: "West Papua",
   CCA3: "",
   Capitol: "Jayapura",
   Region: "Oceania",
   Subregion: "Melanesia",
   French: "Papouasie occidentale",
   Spanish: "Papúa Occidental",
   Russian: "Западное Папуа",
   FlagAltText:
     "A red vertical stripe with a white star, and blue and white horizontal stripes, known as the Morning Star flag.",
   Population: 4000000,
 },
 {
   CommonName: "Tibet",
   OfficialName: "Tibet Autonomous Region",
   CCA3: "",
   Capitol: "Lhasa",
   Region: "Asia",
   Subregion: "Central Asia",
   French: "Tibet",
   Spanish: "Tíbet",
   Russian: "Тибет",
   FlagAltText:
     "A white mountain with a rising sun, two snow lions, and a blue and red striped background.",
   Population: 6000000,
 },
 {
   CommonName: "Sentinelese Territory",
   OfficialName: "North Sentinel Island",
   CCA3: "",
   Capitol: "(none)",
   Region: "Asia",
   Subregion: "Southern Asia",
   French: "Île Sentinel du Nord",
   Spanish: "Isla Sentinel del Norte",
   Russian: "Северный Сентинел",
   FlagAltText: "",
   Population: 100,
 },
 {
   CommonName: "Mi'kma'ki",
   OfficialName: "Mi'kmaq Territory",
   CCA3: "",
   Capitol: "Membertou",
   Region: "Americas",
   Subregion: "North America",
   French: "Mi'kma'ki",
   Spanish: "Mi'kma'ki",
   Russian: "Микмаки",
   FlagAltText:
     "A white field with a red cross and a central star and crescent, representing the Mi'kmaq Grand Council.",
   Population: 17000,
 },
 {
   CommonName: "Naga Homeland",
   OfficialName: "Naga Hills",
   CCA3: "",
   Capitol: "Kohima",
   Region: "Asia",
   Subregion: "South-Eastern Asia",
   French: "Territoire Naga",
   Spanish: "Territorio Naga",
   Russian: "Земля Нагов",
   FlagAltText:
     "A blue, red, and green flag with a rainbow, star, and spear, symbolizing unity and peace.",
   Population: 3500000,
 },
 {
   CommonName: "Aotearoa",
   OfficialName: "Te Ika-a-Māui & Te Waipounamu",
   CCA3: "",
   Capitol: "Rotorua",
   Region: "Oceania",
   Subregion: "Polynesia",
   French: "Territoire Maori",
   Spanish: "Territorio Maorí",
   Russian: "Маори",
   FlagAltText:
     "A black, white, and red koru (spiral) design flag representing new life and growth.",
   Population: 775000,
 },
 {
   CommonName: "Saramaka Territory",
   OfficialName: "Saramaka Maroon Land",
   CCA3: "",
   Capitol: "Asindohopo",
   Region: "Americas",
   Subregion: "South America",
   French: "Terre Saramaka",
   Spanish: "Tierra Saramaka",
   Russian: "Земля Сарамака",
   FlagAltText: "",
   Population: 56000,
 },
 {
   CommonName: "Adivasi Territory",
   OfficialName: "Central Indian Tribal Belt",
   CCA3: "",
   Capitol: "Ranchi",
   Region: "Asia",
   Subregion: "Southern Asia",
   French: "Territoire Adivasi",
   Spanish: "Territorio Adivasi",
   Russian: "Земля Адиваси",
   FlagAltText: "",
   Population: 100000000,
 },
 {
   CommonName: "Tuareg Territory",
   OfficialName: "Azawad",
   CCA3: "",
   Capitol: "Timbuktu",
   Region: "Africa",
   Subregion: "Western Africa",
   French: "Terre Touareg",
   Spanish: "Tierra Tuareg",
   Russian: "Земля Туарегов",
   FlagAltText:
     "A blue field with a red Tifinagh letter yaz, symbolizing freedom.",
   Population: 3500000,
 },
 {
   CommonName: "Sahrawi Land",
   OfficialName: "Western Sahara",
   CCA3: "",
   Capitol: "Laayoune",
   Region: "Africa",
   Subregion: "Northern Africa",
   French: "Sahara occidental",
   Spanish: "Sáhara Occidental",
   Russian: "Западная Сахара",
   FlagAltText:
     "A tricolor of black, white, and green with a red triangle and star/crescent.",
   Population: 600000,
 },
 {
   CommonName: "Yanomami Territory",
   OfficialName: "Yanomami Land",
   CCA3: "",
   Capitol: "Demini",
   Region: "Americas",
   Subregion: "South America",
   French: "Terre Yanomami",
   Spanish: "Tierra Yanomami",
   Russian: "Земля Яномами",
   FlagAltText: "",
   Population: 45000,
 },
];


export default localData;





